<?php

declare(strict_types=1);

return [
    'http://www.w3.org/2001/XMLSchema' => [
        'all' => '\SimpleSAML\XSD\XML\xsd\All',
        'annotation' => '\SimpleSAML\XSD\XML\xsd\Annotation',
        'any' => '\SimpleSAML\XSD\XML\xsd\Any',
        'anyAttribute' => '\SimpleSAML\XSD\XML\xsd\AnyAttribute',
        'appinfo' => '\SimpleSAML\XSD\XML\xsd\Appinfo',
        'attribute' => '\SimpleSAML\XSD\XML\xsd\Attribute',
        'attributeGroup' => '\SimpleSAML\XSD\XML\xsd\NamedAttributeGroup',
        'choice' => '\SimpleSAML\XSD\XML\xsd\Choice',
        'complexContent' => '\SimpleSAML\XSD\XML\xsd\ComplexContent',
        'complexType' => '\SimpleSAML\XSD\XML\xsd\TopLevelComplexType',
        'documentation' => '\SimpleSAML\XSD\XML\xsd\Documentation',
//        'element' => '\SimpleSAML\XSD\XML\xsd\Element',
        'enumeration' => '\SimpleSAML\XSD\XML\xsd\Enumeration',
        'field' => '\SimpleSAML\XSD\XML\xsd\Field',
        'fractionDigits' => '\SimpleSAML\XSD\XML\xsd\FractionDigits',
        'group' => '\SimpleSAML\XSD\XML\xsd\NamedGroup',
        'import' => '\SimpleSAML\XSD\XML\xsd\Import',
        'include' => '\SimpleSAML\XSD\XML\xsd\XsInclude',
        'key' => '\SimpleSAML\XSD\XML\xsd\Key',
        'keyref' => '\SimpleSAML\XSD\XML\xsd\Keyref',
        'length' => '\SimpleSAML\XSD\XML\xsd\Length',
        'list' => '\SimpleSAML\XSD\XML\xsd\XsList',
        'maxExclusive' => '\SimpleSAML\XSD\XML\xsd\MaxExclusive',
        'maxInclusive' => '\SimpleSAML\XSD\XML\xsd\MaxInclusive',
        'maxLength' => '\SimpleSAML\XSD\XML\xsd\MaxLength',
        'minExclusive' => '\SimpleSAML\XSD\XML\xsd\MinExclusive',
        'minInclusive' => '\SimpleSAML\XSD\XML\xsd\MinInclusive',
        'minLength' => '\SimpleSAML\XSD\XML\xsd\MinLength',
        'notation' => '\SimpleSAML\XSD\XML\xsd\Notation',
        'pattern' => '\SimpleSAML\XSD\XML\xsd\Pattern',
//        'redefine' => '\SimpleSAML\XSD\XML\xsd\Redefine',
        'restriction' => '\SimpleSAML\XSD\XML\xsd\Restriction',
//        'schema' => '\SimpleSAML\XSD\XML\xsd\Schema',
        'selector' => '\SimpleSAML\XSD\XML\xsd\Selector',
        'sequence' => '\SimpleSAML\XSD\XML\xsd\Sequence',
        'simpleContent' => '\SimpleSAML\XSD\XML\xsd\SimpleContent',
        'simpleType' => '\SimpleSAML\XSD\XML\xsd\TopLevelSimpleType',
        'totalDigits' => '\SimpleSAML\XSD\XML\xsd\TotalDigits',
        'union' => '\SimpleSAML\XSD\XML\xsd\Union',
        'unique' => '\SimpleSAML\XSD\XML\xsd\Unique',
        'whiteSpace' => '\SimpleSAML\XSD\XML\xsd\WhiteSpace',
    ],
];
